### ISSUE TITLE
ブランチ名にチケット番号がなかったときにエラーじゃなくて無視したい

### ISSUE THREAD

**Issue by 024407** [mana544/sync-pr-to-redmine#4]
release -> main へのプルリク時にアクションが走るとエラーが出てしまう。
無視してパスしたい。

**Comment by mana544** [comment]
### check-behavior オプションの新設

以下のチェックに対して、どのように終了するかの挙動を設定できるようにします。

* pull_request イベント外からの呼び出し
* プルリクアクション 'opened', 'reopened', 'closed'以外からの呼び出し
* ブランチ名解析ができなかった

| option value | description |
| --- | --- |
| 'error' (Default) | エラーを送出して終了します。アクションは失敗します。 |
| 'warning' | warningメッセージを送出して終了します。アクションは成功します。 |

redmine API, Github APIのレスポンスエラーはこの挙動にかかわらずエラー(アクション失敗)となります。

**Comment by mana544** [comment]
developブランチにマージしました。
release -> main でチェックして、検証してください。
検証が終了したら、mainにマージして `v1.1.0` としてリリースします。

**Comment by 024407** [comment]
検証終了。問題なく動作することを確認しました。
